<a href="https://colab.research.google.com/github/Givenmak-7/DataSciencePracticals/blob/Pandas_DataFrame_Practical/Pandas_DataFrame_Practical_empty.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas DataFrame practical

italicized text## CSV / Excel sheet --> DataFrame

Upload the Excel sheet "sample_sales.xlsx" to your GC Notebook (either by uploading the file or by mounting your Google Drive)

In [155]:
# enter code here (if necessary)
import pandas as pd
data1 = pd.read_excel('/content/sample_sales.xlsx', sheet_name = 'Sample_Sales_1')

Create a dataframe **`df1`** from the first sheet of the "sample_sales.xlsx" Excel file.

In [156]:
# enter code here
df1 = pd.DataFrame(data1)
df1.head()

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Russia,Office Supplies,L,2014-05-02,933903.84,~
1,Australia and Oceania,Tuvalu,Baby Food,H,2010-05-28,1582243.50,951410.5
2,~,Sao Tome and Principe,Fruits,C,2014-06-20,56065.84,19525.82
3,Central America and the Caribbean,Grenada,Cereal,C,2012-08-22,328376.44,248406.36
4,Europe,Russia,Office Supplies,L,2014-05-02,933903.84,~

Create a dataframe **`df2`** from the second sheet of the Excel file.
* Note that this dataset does not have any headings.
* Add the same headings to this dataframe as in the first sheet:

"Region", "Country", "Item Type", "Order Priority", "Order Date", "Total Cost", "Total Profit"

In [157]:
# enter code here
header_names = ["Region", "Country", "Item Type", "Order Priority", "Order Date", "Total Cost", "Total Profit"]
data2 = pd.read_excel('/content/sample_sales.xlsx', sheet_name = 'Sample_Sales_2', header = None, names = header_names)
df2 = pd.DataFrame(data2)
df2.head()

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Monaco,Baby Food,H,2012-05-29 00:00:00,1373243.88,825738.04
1,Australia and Oceania,Samoa,Cosmetics,H,2013-07-20 00:00:00,2542187.82,1678540.98
2,Europe,Spain,Household,L,2012-10-21 00:00:00,2267963.02,747939.49
3,Middle East and North Africa,Lebanon,Clothes,L,2012-31-09,282562.56,579000.96
4,Middle East and North Africa,Iran,Cosmetics,H,2016-15-13,1708748.37,1128242.43

Create a dataframe **`df3`** from the third sheet of the Excel file.
* Note that you will need to skip the first few lines

In [158]:
# enter code here
data3 = pd.read_excel('/content/sample_sales.xlsx', sheet_name = 'Sample_Sales_3', skiprows= 4)
df3 = pd.DataFrame(data3)
df3.head()

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Middle East and North Africa,Azerbaijan,Office Supplies,M,2012-06-13,1060944.16,255151.25
1,Europe,Romania,Cosmetics,H,2010-11-26,2082940.30,1375311.70
2,Central America and the Caribbean,Nicaragua,Beverages,C,2011-02-05,259279.24,127722.96
3,Sub-Saharan Africa,Mali,Clothes,M,2011-07-26,31825.92,65214.72
4,Asia,Malaysia,Fruits,L,2011-11-11,43367.64,15103.47

Create a dataframe **`df_concat_13`** that concatenates the dataframes **`df1`** and **`df3`** on the row axis.

NB: remember to reset your index!

In [159]:
# enter code here

df_concat_13 = pd.concat([df1, df3], axis =0)
df_concat_13 = df_concat_13.reset_index()
df_concat_13

,index,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,0,Europe,Russia,Office Supplies,L,2014-05-02,933903.84,~
1,1,Australia and Oceania,Tuvalu,Baby Food,H,2010-05-28,1582243.50,951410.5
2,2,~,Sao Tome and Principe,Fruits,C,2014-06-20,56065.84,19525.82
3,3,Central America and the Caribbean,Grenada,Cereal,C,2012-08-22,328376.44,248406.36
4,4,Europe,Russia,Office Supplies,L,2014-05-02,933903.84,~
5,5,Sub-Saharan Africa,Sao Tome and Principe,Fruits,C,2014-06-20,56065.84,19525.82
6,6,Sub-Saharan Africa,Rwanda,Office Supplies,L,2013-02-01,2657347.52,639077.5
7,7,Australia and Oceania,Solomon Islands,Baby Food,C,2015-02-04,474115.08,285087.64
8,8,Sub-Saharan Africa,Angola,Household,M,2011-04-23,2104134.98,~
9,9,Sub-Saharan Africa,Angola,Household,M,2011-04-23,2104134.98,~
10,10,Sub-Saharan Africa,~,Vegetables,H,2012-07-17,734896.26,510216.66
11,11,Sub-Saharan Africa,Republic of the Congo,Personal Care,M,2015-07-14,343986.90,152114.2
12,12,Sub-Saharan Africa,Senegal,Cereal,H,2014-04-18,772106.23,584073.87
13,13,Asia,Kyrgyzstan,Vegetables,H,2011-06-24,11275.32,~
14,14,Sub-Saharan Africa,Cape Verde,Clothes,H,2014-08-02,149381.12,306097.92
15,15,Asia,Bangladesh,Clothes,L,2017-01-13,296145.92,606834.72
16,16,Europe,Bulgaria,Clothes,M,2012-04-23,59960.32,122865.12
17,17,Central America and the Caribbean,Honduras,Household,H,2017-02-08,4509793.96,1487261.02
18,18,Asia,Mongolia,Personal Care,C,2014-02-19,277739.67,122819.06
19,19,Europe,Bulgaria,Clothes,M,2012-04-23,59960.32,122865.12
20,20,Asia,Sri Lanka,Cosmetics,M,2016-11-19,1830670.16,1208744.24
21,21,Sub-Saharan Africa,Cameroon,Beverages,C,2015-04-01,172619.70,85033.8
22,22,Asia,Turkmenistan,Household,L,2010-12-30,1924728.20,634745.9
23,23,Australia and Oceania,East Timor,Meat,L,2012-07-31,2154588.52,337937.6
24,24,Europe,Norway,Baby Food,L,2014-05-14,1187679.00,714157
25,25,Sub-Saharan Africa,The Gambia,Household,L,2012-05-26,1191019.80,392780.1
26,26,Europe,Portugal,Baby Food,H,2015-07-31,202941.66,122029.78
27,27,Central America and the Caribbean,Honduras,Snacks,L,2016-06-30,216804.00,122686.5
28,28,Australia and Oceania,New Zealand,Fruits,H,2014-09-08,15134.04,5270.67
29,29,Europe,Moldova,Personal Care,L,2016-05-07,287316.90,127054.2
30,30,Europe,France,Cosmetics,H,2017-05-22,477943.95,315574.05
31,31,Australia and Oceania,Kiribati,Fruits,M,2014-10-13,37354.16,13009.18
32,32,Sub-Saharan Africa,Mali,Fruits,L,2010-05-07,40288.24,14031.02
33,33,Europe,Norway,Beverages,C,2014-07-18,162891.96,80241.84
34,34,Sub-Saharan Africa,The Gambia,Household,L,2012-05-26,1191019.80,392780.1
35,35,Europe,Switzerland,Cosmetics,M,2012-09-17,2280701.13,1505888.07
36,36,Sub-Saharan Africa,South Sudan,Personal Care,C,2013-12-29,120423.75,53252.5
37,37,Australia and Oceania,Australia,Office Supplies,C,2015-10-27,1534983.04,369155
38,38,Asia,Myanmar,Household,H,2015-01-16,4145955.00,1367272.5
39,39,Sub-Saharan Africa,Djibouti,Snacks,M,2017-02-25,713942.88,404010.78
40,40,Central America and the Caribbean,Costa Rica,Personal Care,L,2017-05-08,363198.03,160609.54
41,41,Middle East and North Africa,Syria,Fruits,L,2011-11-22,26185.28,9119.44
42,42,Sub-Saharan Africa,The Gambia,Meat,M,2017-01-14,1738477.23,272672.4
43,43,Central America and the Caribbean,Costa Rica,Personal Care,L,2017-05-08,363198.03,160609.54
44,44,Asia,Brunei,Office Supplies,L,2012-04-01,3521431.68,846885
45,45,Europe,Bulgaria,Office Supplies,M,2012-02-16,2093015.52,503358.75
46,46,Sub-Saharan Africa,Niger,Personal Care,H,2017-03-11,170860.05,75555.9
47,47,Middle East and North Africa,Azerbaijan,Cosmetics,M,2010-02-06,1904929.22,1257775.58
48,48,Sub-Saharan Africa,The Gambia,Cereal,H,2012-06-07,247921.87,187545.03
49,0,Middle East and North Africa,Azerbaijan,Office Supplies,M,2012-06-13,1060944.16,255151.25
50,1,Europe,Romania,Cosmetics,H,2010-11-26,2082940.30,1375311.7
51,2,Central America and the Caribbean,Nicaragua,Beverages,C,2011-02-05,259279.24,127722.96
52,3,Sub-Saharan Africa,Mali,Clothes,M,2011-07-26,31825.92,65214.72
53,4,Asia,Malaysia,Fruits,L,2011-11-11,43367.64,15103.47
54,5,Sub-Saharan Africa,Sierra Leone,Vegetables,C,2016-06-01,135031.05,93748.05
55,6,North America,Mexico,Personal Care,M,2015-07-30,326815.89,144521.02
56,7,Sub-Saharan Africa,Mozambique,Household,L,2012-02-10,2697132.18,889472.91

## Replacing and removing

For dataframe **`df1`**, column name "Order Priority":
* replace "H" with "High"
* replace "M" with "Medium"
* replace "L" with "Low"

(Keep the dataframe name **`df1`**)

In [160]:
# Enter code here
df1['Order Priority'] = df1['Order Priority'].replace({'H':'High','M':'Medium','L':'Low'})
df1.head()

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,~
1,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28,1582243.50,951410.5
2,~,Sao Tome and Principe,Fruits,C,2014-06-20,56065.84,19525.82
3,Central America and the Caribbean,Grenada,Cereal,C,2012-08-22,328376.44,248406.36
4,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,~

For dataframe **`df1`**, replace all entries containing '~' with NaN values.

NB: remember to import the numpy library!

In [161]:
# Enter code here
import numpy as np

df1 = df1.replace('~', np.nan)
df1.head()

/tmp/ipython-input-161-2646201687.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1 = df1.replace('~', np.nan)

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,NaN
1,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28,1582243.50,951410.50
2,NaN,Sao Tome and Principe,Fruits,C,2014-06-20,56065.84,19525.82
3,Central America and the Caribbean,Grenada,Cereal,C,2012-08-22,328376.44,248406.36
4,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,NaN

For dataframe **`df1`**, remove all rows in the dataframe where there is a "C" in the "Order Priority" column

NB: remember to reset your index!

In [162]:
# Enter code here
df1 = df1[df1['Order Priority'] != "C"].reset_index(drop=True)

df1

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,NaN
1,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28,1582243.50,951410.50
2,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,NaN
3,Sub-Saharan Africa,Rwanda,Office Supplies,Low,2013-02-01,2657347.52,639077.50
4,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23,2104134.98,NaN
5,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23,2104134.98,NaN
6,Sub-Saharan Africa,NaN,Vegetables,High,2012-07-17,734896.26,510216.66
7,Sub-Saharan Africa,Republic of the Congo,Personal Care,Medium,2015-07-14,343986.90,152114.20
8,Sub-Saharan Africa,Senegal,Cereal,High,2014-04-18,772106.23,584073.87
9,Asia,Kyrgyzstan,Vegetables,High,2011-06-24,11275.32,NaN
10,Sub-Saharan Africa,Cape Verde,Clothes,High,2014-08-02,149381.12,306097.92
11,Asia,Bangladesh,Clothes,Low,2017-01-13,296145.92,606834.72
12,Europe,Bulgaria,Clothes,Medium,2012-04-23,59960.32,122865.12
13,Central America and the Caribbean,Honduras,Household,High,2017-02-08,4509793.96,1487261.02
14,Europe,Bulgaria,Clothes,Medium,2012-04-23,59960.32,122865.12
15,Asia,Sri Lanka,Cosmetics,Medium,2016-11-19,1830670.16,1208744.24
16,Asia,Turkmenistan,Household,Low,2010-12-30,1924728.20,634745.90
17,Australia and Oceania,East Timor,Meat,Low,2012-07-31,2154588.52,337937.60
18,Europe,Norway,Baby Food,Low,2014-05-14,1187679.00,714157.00
19,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26,1191019.80,392780.10
20,Europe,Portugal,Baby Food,High,2015-07-31,202941.66,122029.78
21,Central America and the Caribbean,Honduras,Snacks,Low,2016-06-30,216804.00,122686.50
22,Australia and Oceania,New Zealand,Fruits,High,2014-09-08,15134.04,5270.67
23,Europe,Moldova,Personal Care,Low,2016-05-07,287316.90,127054.20
24,Europe,France,Cosmetics,High,2017-05-22,477943.95,315574.05
25,Australia and Oceania,Kiribati,Fruits,Medium,2014-10-13,37354.16,13009.18
26,Sub-Saharan Africa,Mali,Fruits,Low,2010-05-07,40288.24,14031.02
27,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26,1191019.80,392780.10
28,Europe,Switzerland,Cosmetics,Medium,2012-09-17,2280701.13,1505888.07
29,Asia,Myanmar,Household,High,2015-01-16,4145955.00,1367272.50
30,Sub-Saharan Africa,Djibouti,Snacks,Medium,2017-02-25,713942.88,404010.78
31,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08,363198.03,160609.54
32,Middle East and North Africa,Syria,Fruits,Low,2011-11-22,26185.28,9119.44
33,Sub-Saharan Africa,The Gambia,Meat,Medium,2017-01-14,1738477.23,272672.40
34,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08,363198.03,160609.54
35,Asia,Brunei,Office Supplies,Low,2012-04-01,3521431.68,846885.00
36,Europe,Bulgaria,Office Supplies,Medium,2012-02-16,2093015.52,503358.75
37,Sub-Saharan Africa,Niger,Personal Care,High,2017-03-11,170860.05,75555.90
38,Middle East and North Africa,Azerbaijan,Cosmetics,Medium,2010-02-06,1904929.22,1257775.58
39,Sub-Saharan Africa,The Gambia,Cereal,High,2012-06-07,247921.87,187545.03

Create a dataframe **`df_cereal`**. This dataframe should only contain the rows of **`df1`** where the "Item Type" entry is "Cereal"
* remember to reset the index

In [163]:
# Enter code here
df_cereal = df1[df1["Item Type"] == "Cereal"].reset_index(drop=True)
df_cereal

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Sub-Saharan Africa,Senegal,Cereal,High,2014-04-18,772106.23,584073.87
1,Sub-Saharan Africa,The Gambia,Cereal,High,2012-06-07,247921.87,187545.03

Remove the column "Total Cost" and "Total Profit" in dataframe **`df1`**.

(Keep the dataframe name **`df1`**)

In [164]:
# Enter code here
df1 = df1.drop(["Total Cost","Total Profit"], axis =1)
df1

,Region,Country,Item Type,Order Priority,Order Date
0,Europe,Russia,Office Supplies,Low,2014-05-02
1,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28
2,Europe,Russia,Office Supplies,Low,2014-05-02
3,Sub-Saharan Africa,Rwanda,Office Supplies,Low,2013-02-01
4,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23
5,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23
6,Sub-Saharan Africa,NaN,Vegetables,High,2012-07-17
7,Sub-Saharan Africa,Republic of the Congo,Personal Care,Medium,2015-07-14
8,Sub-Saharan Africa,Senegal,Cereal,High,2014-04-18
9,Asia,Kyrgyzstan,Vegetables,High,2011-06-24
10,Sub-Saharan Africa,Cape Verde,Clothes,High,2014-08-02
11,Asia,Bangladesh,Clothes,Low,2017-01-13
12,Europe,Bulgaria,Clothes,Medium,2012-04-23
13,Central America and the Caribbean,Honduras,Household,High,2017-02-08
14,Europe,Bulgaria,Clothes,Medium,2012-04-23
15,Asia,Sri Lanka,Cosmetics,Medium,2016-11-19
16,Asia,Turkmenistan,Household,Low,2010-12-30
17,Australia and Oceania,East Timor,Meat,Low,2012-07-31
18,Europe,Norway,Baby Food,Low,2014-05-14
19,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26
20,Europe,Portugal,Baby Food,High,2015-07-31
21,Central America and the Caribbean,Honduras,Snacks,Low,2016-06-30
22,Australia and Oceania,New Zealand,Fruits,High,2014-09-08
23,Europe,Moldova,Personal Care,Low,2016-05-07
24,Europe,France,Cosmetics,High,2017-05-22
25,Australia and Oceania,Kiribati,Fruits,Medium,2014-10-13
26,Sub-Saharan Africa,Mali,Fruits,Low,2010-05-07
27,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26
28,Europe,Switzerland,Cosmetics,Medium,2012-09-17
29,Asia,Myanmar,Household,High,2015-01-16
30,Sub-Saharan Africa,Djibouti,Snacks,Medium,2017-02-25
31,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08
32,Middle East and North Africa,Syria,Fruits,Low,2011-11-22
33,Sub-Saharan Africa,The Gambia,Meat,Medium,2017-01-14
34,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08
35,Asia,Brunei,Office Supplies,Low,2012-04-01
36,Europe,Bulgaria,Office Supplies,Medium,2012-02-16
37,Sub-Saharan Africa,Niger,Personal Care,High,2017-03-11
38,Middle East and North Africa,Azerbaijan,Cosmetics,Medium,2010-02-06
39,Sub-Saharan Africa,The Gambia,Cereal,High,2012-06-07

Some of the entries in **`df1`** are duplicates.
If the same "Country" and "Item type" entries appear in more than one row, only keep the **`last`** entry and remove the rest of the duplicates. Keep the name of the dataframe **`df1`**
* remember to reset the index

In [165]:
# Enter code here
df1 = df1.drop_duplicates(subset=['Country', 'Item Type'], keep='last').reset_index(drop=True)
df1

,Region,Country,Item Type,Order Priority,Order Date
0,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28
1,Europe,Russia,Office Supplies,Low,2014-05-02
2,Sub-Saharan Africa,Rwanda,Office Supplies,Low,2013-02-01
3,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23
4,Sub-Saharan Africa,NaN,Vegetables,High,2012-07-17
5,Sub-Saharan Africa,Republic of the Congo,Personal Care,Medium,2015-07-14
6,Sub-Saharan Africa,Senegal,Cereal,High,2014-04-18
7,Asia,Kyrgyzstan,Vegetables,High,2011-06-24
8,Sub-Saharan Africa,Cape Verde,Clothes,High,2014-08-02
9,Asia,Bangladesh,Clothes,Low,2017-01-13
10,Central America and the Caribbean,Honduras,Household,High,2017-02-08
11,Europe,Bulgaria,Clothes,Medium,2012-04-23
12,Asia,Sri Lanka,Cosmetics,Medium,2016-11-19
13,Asia,Turkmenistan,Household,Low,2010-12-30
14,Australia and Oceania,East Timor,Meat,Low,2012-07-31
15,Europe,Norway,Baby Food,Low,2014-05-14
16,Europe,Portugal,Baby Food,High,2015-07-31
17,Central America and the Caribbean,Honduras,Snacks,Low,2016-06-30
18,Australia and Oceania,New Zealand,Fruits,High,2014-09-08
19,Europe,Moldova,Personal Care,Low,2016-05-07
20,Europe,France,Cosmetics,High,2017-05-22
21,Australia and Oceania,Kiribati,Fruits,Medium,2014-10-13
22,Sub-Saharan Africa,Mali,Fruits,Low,2010-05-07
23,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26
24,Europe,Switzerland,Cosmetics,Medium,2012-09-17
25,Asia,Myanmar,Household,High,2015-01-16
26,Sub-Saharan Africa,Djibouti,Snacks,Medium,2017-02-25
27,Middle East and North Africa,Syria,Fruits,Low,2011-11-22
28,Sub-Saharan Africa,The Gambia,Meat,Medium,2017-01-14
29,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08
30,Asia,Brunei,Office Supplies,Low,2012-04-01
31,Europe,Bulgaria,Office Supplies,Medium,2012-02-16
32,Sub-Saharan Africa,Niger,Personal Care,High,2017-03-11
33,Middle East and North Africa,Azerbaijan,Cosmetics,Medium,2010-02-06
34,Sub-Saharan Africa,The Gambia,Cereal,High,2012-06-07

## Dates

Consider dataframe **`df2`**.
Change the Order Date column to a pandas datetime, with the format: year-month-day

(Keep the dataframe name **`df2`**)

* remember to add code that would allow for incorrect dates to be displayed as "NaT"

In [166]:
# Enter code here
df2['Order Date'] = pd.to_datetime(df2['Order Date'], format= '%Y-%m-%d', errors='coerce')
df2

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Monaco,Baby Food,H,2012-05-29,1373243.88,825738.04
1,Australia and Oceania,Samoa,Cosmetics,H,2013-07-20,2542187.82,1678540.98
2,Europe,Spain,Household,L,2012-10-21,2267963.02,747939.49
3,Middle East and North Africa,Lebanon,Clothes,L,NaT,282562.56,579000.96
4,Middle East and North Africa,Iran,Cosmetics,H,NaT,1708748.37,1128242.43
5,Sub-Saharan Africa,Zambia,Snacks,L,2011-01-04,398042.40,225246.90
6,Sub-Saharan Africa,Kenya,Vegetables,L,2012-03-18,587135.01,407630.41
7,North America,Mexico,Personal Care,L,2012-02-17,363934.74,160935.32
8,Sub-Saharan Africa,Sao Tome and Principe,Beverages,C,2011-01-16,280673.91,138262.14
9,Sub-Saharan Africa,The Gambia,Baby Food,M,2014-02-03,886215.78,532885.74
10,Middle East and North Africa,Kuwait,Fruits,M,2012-04-30,3612.24,1258.02
11,Europe,Slovenia,Beverages,C,2016-10-23,148141.40,72975.60
12,Sub-Saharan Africa,Sierra Leone,Office Supplies,H,2016-12-06,497662.08,119685.00
13,Australia and Oceania,Australia,Beverages,H,2014-07-07,298476.31,147031.74

Remove all the rows in **`df2`** that contain NaT values in your "Order Date" column.

(Keep the dataframe name **df2**)

* NB: since you removed some rows, remember to reset your index!

In [168]:
# Enter code here
df2 = df2[df2['Order Date'].notna()].reset_index(drop=True)
df2

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Monaco,Baby Food,H,2012-05-29,1373243.88,825738.04
1,Australia and Oceania,Samoa,Cosmetics,H,2013-07-20,2542187.82,1678540.98
2,Europe,Spain,Household,L,2012-10-21,2267963.02,747939.49
3,Sub-Saharan Africa,Zambia,Snacks,L,2011-01-04,398042.40,225246.90
4,Sub-Saharan Africa,Kenya,Vegetables,L,2012-03-18,587135.01,407630.41
5,North America,Mexico,Personal Care,L,2012-02-17,363934.74,160935.32
6,Sub-Saharan Africa,Sao Tome and Principe,Beverages,C,2011-01-16,280673.91,138262.14
7,Sub-Saharan Africa,The Gambia,Baby Food,M,2014-02-03,886215.78,532885.74
8,Middle East and North Africa,Kuwait,Fruits,M,2012-04-30,3612.24,1258.02
9,Europe,Slovenia,Beverages,C,2016-10-23,148141.40,72975.60
10,Sub-Saharan Africa,Sierra Leone,Office Supplies,H,2016-12-06,497662.08,119685.00
11,Australia and Oceania,Australia,Beverages,H,2014-07-07,298476.31,147031.74

## Dataframe --> CSV / Excel sheet

Write dataframe df1 to a csv named 'dataframe_1' and write it to your Drive

In [175]:
# Enter code here
from google.colab import drive
drive.mount('/content/drive')

df1.to_csv('/content/drive/My Drive/dataframe_1.csv', index=False)

Mounted at /content/drive

Write dataframe df2 to an excel sheet named 'dataframe_2' and write it to your Drive

In [177]:
# Enter code here
df2.to_excel('/content/drive/My Drive/dataframe_2.xlsx', index=False)